server.port=8081

# --- Kết nối Database ---
spring.datasource.url=jdbc:mysql://localhost:3306/planbook_ai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Hibernate Settings ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Cấu hình File Upload ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# --- Fix lỗi Swagger 500 ---
springdoc.packages-to-scan=com.planbookai.ocr.controller
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Gemini API Key
gemini.api.key=AIzaSyBB2d1rRVnE8bSOdE3su1RcsB_c5seIoQo